version: '3.8'

services:

  webserver:
    image: "${WEBSERVER_IMAGE-web/webserver}:${WEBSERVER_TAG-local}"
    build:
      dockerfile: Dockerfile
      target: webserver
      context: .
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == worker]

  application:
    image: "${APPLICATION_IMAGE-web/application}:${APPLICATION_TAG-local}"
    build:
      dockerfile: Dockerfile
      target: application_production
      context: .
    deploy:
      replicas: 2
      placement:
        constraints: [node.role == worker]
