services:

  application:
    image: "docker-php/php-demo:local"
    build:
      dockerfile: ./.include/php/Dockerfile
      target: app_development
      context: .
    volumes:
      - ./srcs:/var/www/html:ro
    deploy:
      replicas: 2

  proxy:
    image: "docker-php/nginx-php:local"
    build:
      dockerfile: ./.include/nginx/Dockerfile
      target: default
      context: .
    volumes:
      - ./assets/img:/var/www/html/img:ro
      - ./assets/logo:/var/www/html/logo:ro
    ports:
      - 80:80
    deploy:
      replicas: 2
