services:

  application:
    image: "${APPLICATION_IMAGE-web/application}:${APPLICATION_TAG-local}"
    build:
      dockerfile: ./.docker/Dockerfile.php
      target: app_development
      context: .
    volumes:
      - ./srcs:/var/www/html:ro
    deploy:
      replicas: 2

  webserver:
    image: "${WEBSERVER_IMAGE-web/webserver}:${WEBSERVER_TAG-local}"
    build:
      dockerfile: ./.docker/Dockerfile.nginx
      target: default
      context: .
    volumes:
      - ./assets/img:/var/www/html/img:ro
      - ./assets/logo:/var/www/html/logo:ro
    ports:
      - 80:80
      - 443:443
    deploy:
      replicas: 1
