version: '3.8'

services:

  webserver:
    image: "web/webserver:${TAG-local}"
    build:
      dockerfile: Dockerfile
      target: webserver
      context: .
    ports:
      - 80:80
      - 443:443

  application:
    image: "web/application:${TAG-local}"
    build:
      dockerfile: Dockerfile
      target: application_production
      context: .
    deploy:
      replicas: 2
