version: '3.8'

services:

  webserver:
    extends:
      file: docker-compose.base.yml
      service: webserver
    volumes:
      - ./assets/img:/var/www/html/img:ro
      - ./assets/logo:/var/www/html/logo:ro

  application:
    extends:
      file: docker-compose.base.yml
      service: application
    build:
      target: application_development
    environment:
      XDEBUG_MODE: "debug"
    volumes:
      - ./srcs:/var/www/html:ro
