services:

  application:
    image: "${APPLICATION_REPO:+${APPLICATION_REPO}/}${APPLICATION_IMAGE?}:${APPLICATION_TAG?}"
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.platform.os == linux
          - node.role == worker
      update_config:
        order: start-first

  webserver:
    image: "${WEBSERVER_REPO:+${WEBSERVER_REPO}/}${WEBSERVER_IMAGE?}:${WEBSERVER_TAG?}"
    networks:
      - default
      - traefik
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.platform.os == linux
          - node.role == worker
      update_config:
        order: start-first
      labels:
        traefik.enable: "true"
        traefik.http.routers.${APPLICATION_NAME}.rule: "Host(`${APPLICATION_URL}`)"
        traefik.http.routers.${APPLICATION_NAME}.entrypoints: "web,websecure"
        traefik.http.services.${APPLICATION_NAME}.loadbalancer.server.port: 80

networks:
  traefik:
    external: true
