services:

  application:
    image: "${APPLICATION_IMAGE?}"
    deploy:
      replicas: 3
      placement:
        constraints:
          - node.platform.os == linux
          - node.role == worker
      update_config:
        order: start-first
      resources:
        reservations:
          cpus: "0.06"
          memory: "128MB"
        limits:
          cpus: "0.25"
          memory: 512MB

  proxy:
    image: "${PROXY_IMAGE?}"
    networks:
      - default
      - traefik
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.platform.os == linux
          - node.role == worker
      update_config:
        order: start-first
      labels:
        - traefik.enable=true
        - traefik.http.routers.${APPLICATION_NAME}.rule=Host(`${APPLICATION_URL}`)
        - traefik.http.routers.${APPLICATION_NAME}.entrypoints=web,websecure
        - traefik.http.services.${APPLICATION_NAME}.loadbalancer.server.port=80
      resources:
        reservations:
          cpus: "0.06"
          memory: "30MB"
        limits:
          cpus: "0.25"
          memory: "128M"

  proxy_metrics:
    image: nginx/nginx-prometheus-exporter:1.4.0
    command:
      - --nginx.scrape-uri=http://proxy/status_nginx
    networks:
      - default
      - metrics

networks:
  traefik:
    external: true
  metrics:
    external: true
