version: '3.8'

services:

  application:
    image: "${APPLICATION_IMAGE-web/application}:${APPLICATION_TAG-local}"
    deploy:
      replicas: 2
      placement:
        constraints: [node.role == worker]

  webserver:
    image: "${WEBSERVER_IMAGE-web/webserver}:${WEBSERVER_TAG-local}"
    ports:
      - 80:80
      - 443:443
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == worker]
