name: Build images

on:
  push:
    branches:
      - "*"
    paths:
      - ".include/**"
      - "docker-compose*.yml"
      - "Dockerfile"
      - ".github/workflows/images.yml"
  pull_request:
    types: [opened, synchronize]
    branches:
      - "*"
    paths:
      - ".include/**"
      - "docker-compose.base.yml"
      - "Dockerfile"
      - ".github/workflows/images.yml"
  workflow_dispatch:

env:
    REGISTRY_IMAGE: ${{ vars.DOCKER_REGISTRY_URL }}/${{ github.actor }}/web
    IMAGE_PHP_BASE_NAME: php
    IMAGE_PHP_APP_NAME: app
    IMAGE_WEBSERVER_NAME: webserver

jobs:

  docker_image_build_base:
    name: "Base - Build Docker"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
        php_major:
          - "5"
          - "7"
          - "8"
        php_environnement:
          - "production"
          - "development"

    steps:
      - name: Prepare
        run: |
          platform=${{ matrix.platform }}
          echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY_IMAGE }}/${{ env.IMAGE_PHP_BASE_NAME }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.DOCKER_REGISTRY_URL }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker image Build
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: ${{ matrix.platform }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: mode=max
          build-args: |
            PHP_MAJOR=${{ matrix.php_major }}
          target: php_${{ matrix.php_environnement }}
          outputs: type=image,name=${{ env.REGISTRY_IMAGE }}/${{ env.IMAGE_PHP_BASE_NAME }},push-by-digest=true,name-canonical=true,push=true

      - name: Export digest
        run: |
          mkdir -p /tmp/digests
          digest="${{ steps.build.outputs.digest }}"
          touch "/tmp/digests/${digest#sha256:}"

      - name: Upload digest
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.IMAGE_PHP_BASE_NAME }}-${{ matrix.php_major }}-${{ matrix.php_environnement }}-${{ env.PLATFORM_PAIR }}
          path: /tmp/digests/*
          if-no-files-found: error
          retention-days: 1

  docker_image_push_base:
    name: "Base - Push Docker"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php_major:
          - "5"
          - "7"
          - "8"
        php_environnement:
          - "production"
          - "development"
    needs: ["docker_image_build_base"]

    steps:
      - name: Download digests
        uses: actions/download-artifact@v4
        with:
          pattern: ${{ env.IMAGE_PHP_BASE_NAME }}-${{ matrix.php_major }}-${{ matrix.php_environnement }}-*
          path: /tmp/digests
          merge-multiple: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.DOCKER_REGISTRY_URL }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY_IMAGE }}/${{ env.IMAGE_PHP_BASE_NAME }}
          tags: |
            type=raw,value=latest,enable=${{ matrix.php_environnement == 'production' && matrix.php_major == '8' }}
            type=raw,value=production,enable=${{ matrix.php_environnement == 'production' && matrix.php_major == '8' }}
            type=raw,value=development,enable=${{ matrix.php_environnement == 'development' && matrix.php_major == '8' }}
            type=raw,value=${{ matrix.php_major }},enable=${{ matrix.php_environnement == 'production' }}
            type=raw,value=${{ matrix.php_major }}-${{ matrix.php_environnement }}

      - name: Create manifest list and push
        working-directory: /tmp/digests
        run: docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") $(printf '${{ env.REGISTRY_IMAGE }}/${{ env.IMAGE_PHP_BASE_NAME }}@sha256:%s ' *)

  docker_image_build_app:
    name: "App - Build Docker"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
        php_major:
          - "5"
          - "7"
          - "8"
        php_environnement:
          - "production"
          - "development"

    steps:
      - name: Prepare
        run: |
          platform=${{ matrix.platform }}
          echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY_IMAGE }}/${{ env.IMAGE_PHP_APP_NAME }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.DOCKER_REGISTRY_URL }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker image Build
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: ${{ matrix.platform }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: mode=max
          build-args: |
            PHP_MAJOR=${{ matrix.php_major }}
          target: application_${{ matrix.php_environnement }}
          outputs: type=image,name=${{ env.REGISTRY_IMAGE }}/${{ env.IMAGE_PHP_APP_NAME }},push-by-digest=true,name-canonical=true,push=true

      - name: Export digest
        run: |
          mkdir -p /tmp/digests
          digest="${{ steps.build.outputs.digest }}"
          touch "/tmp/digests/${digest#sha256:}"

      - name: Upload digest
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.IMAGE_PHP_APP_NAME }}-${{ matrix.php_major }}-${{ matrix.php_environnement }}-${{ env.PLATFORM_PAIR }}
          path: /tmp/digests/*
          if-no-files-found: error
          retention-days: 1

  docker_image_push_app:
    name: "App - Push Docker"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php_major:
          - "5"
          - "7"
          - "8"
        php_environnement:
          - "production"
          - "development"
    needs: ["docker_image_build_app"]

    steps:
      - name: Download digests
        uses: actions/download-artifact@v4
        with:
          pattern: ${{ env.IMAGE_PHP_APP_NAME }}-${{ matrix.php_major }}-${{ matrix.php_environnement }}-*
          path: /tmp/digests
          merge-multiple: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.DOCKER_REGISTRY_URL }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY_IMAGE }}/${{ env.IMAGE_PHP_APP_NAME }}
          tags: |
            type=raw,value=latest,enable=${{ matrix.php_environnement == 'production' && matrix.php_major == '8' }}
            type=raw,value=production,enable=${{ matrix.php_environnement == 'production' && matrix.php_major == '8' }}
            type=raw,value=development,enable=${{ matrix.php_environnement == 'development' && matrix.php_major == '8' }}
            type=raw,value=${{ matrix.php_major }},enable=${{ matrix.php_environnement == 'production' }}
            type=raw,value=${{ matrix.php_major }}-${{ matrix.php_environnement }}

      - name: Create manifest list and push
        working-directory: /tmp/digests
        run: docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") $(printf '${{ env.REGISTRY_IMAGE }}/${{ env.IMAGE_PHP_APP_NAME }}@sha256:%s ' *)

  docker_image_build_webserver:
    name: "Webserver - Build Docker"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm64

    steps:
      - name: Prepare
        run: |
          platform=${{ matrix.platform }}
          echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY_IMAGE }}/${{ env.IMAGE_WEBSERVER_NAME }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.DOCKER_REGISTRY_URL }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker image Build
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: ${{ matrix.platform }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: mode=max
          target: webserver
          outputs: type=image,name=${{ env.REGISTRY_IMAGE }}/${{ env.IMAGE_WEBSERVER_NAME }},push-by-digest=true,name-canonical=true,push=true

      - name: Export digest
        run: |
          mkdir -p /tmp/digests
          digest="${{ steps.build.outputs.digest }}"
          touch "/tmp/digests/${digest#sha256:}"

      - name: Upload digest
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.IMAGE_WEBSERVER_NAME }}-${{ env.PLATFORM_PAIR }}
          path: /tmp/digests/*
          if-no-files-found: error
          retention-days: 1

  docker_image_push_webserver:
    name: "Webserver - Push Docker"
    runs-on: ubuntu-latest
    needs: ["docker_image_build_webserver"]

    steps:
      - name: Download digests
        uses: actions/download-artifact@v4
        with:
          pattern: ${{ env.IMAGE_WEBSERVER_NAME }}-*
          path: /tmp/digests
          merge-multiple: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.DOCKER_REGISTRY_URL }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY_IMAGE }}/${{ env.IMAGE_WEBSERVER_NAME }}
          tags: |
            type=raw,value=latest

      - name: Create manifest list and push
        working-directory: /tmp/digests
        run: docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") $(printf '${{ env.REGISTRY_IMAGE }}/${{ env.IMAGE_WEBSERVER_NAME }}@sha256:%s ' *)
